# -*- coding: utf-8 -*-
"""EDA_Spotfy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLAszNW48GBnGwjBJA1thECCu-t07PL9

- Ideia inicial é fazer uma análise exploratória dos dados, identificar
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import io #capturar apenas a saida

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
df = pd.read_csv('/content/drive/MyDrive/Spotfy/Spotify Most Streamed Songs.csv')

df.head(10)

buffer = io.StringIO()
df.info(buf=buffer)


summary = pd.DataFrame({
    "Informação": df.dtypes,
    "Cardinalidade": df.nunique(),
    "Valores não nulos": df.notnull().sum(),
    "Dados Nulos": df.isnull().sum()
    })

print(summary)

"""### Informações básicas:

- **track_name:** Nome do som.
- **artist(s)_name:** Nome do artista(s).
- **artist_count:** Number of artists contributing to the song.
- **released_year, released_month, released_day:** Detalhes da data de lançamento.

### Métricas de streaming:

- **in_spotify_playlists:** Número de playlists do Spotify em que a música aparece.
- **in_spotify_charts:** Classificação da música nas paradas do Spotify.
- **streams:** Número total de transmissões no Spotify.
- **in_apple_playlists, in_apple_charts:** Presença em playlists e paradas do Apple Music.
- **in_deezer_playlists, in_deezer_charts:** Presença em playlists e paradas do Deezer.
- **in_shazam_charts:** Classifique nas paradas do Shazam.

### Musical Attributes

- **bpm:** Batidas por minuto, representando o ritmo (tempo) da música.
- **key:** Tom da música.
- **mode:** Indica se a música está em modo maior ou menor.
- **danceability_%:** Adequação da música para dançar.
- **valence_%:** Positividade do conteúdo musical da canção.
- **energy_%:** Nível de energia percebido na música.
- **acousticness_%:** Presença de sons acústicos na canção.
- **instrumentalness_%:** Proporção de conteúdo instrumental na faixa.
- **liveness_%:** Presença de elementos de performance ao vivo.
- **speechiness_%:** Quantidade de palavras faladas na música.
"""

# 'in_deezer_playlist esta inicialmente em OBJECT
# As colunas 'released_year', 'released_month' e 'released_day' estão fora da formatação de data
df['in_deezer_playlists'] = pd.to_numeric(df['in_deezer_playlists'], errors= 'coerce').fillna(0).astype(int)
df['in_deezer_charts'] = pd.to_numeric(df['in_deezer_charts'], errors= 'coerce').fillna(0).astype(int)
df['in_shazam_charts'] = pd.to_numeric(df['in_shazam_charts'], errors= 'coerce')
#df['streams'] = pd.to_numeric(df['streams'].astype(int))

df['released_date'] = pd.to_datetime(df['released_year'].astype(str)+ '-' +
                                     df['released_month'].astype(str)+ '-' +
                                     df['released_day'].astype(str))

#União colunas str
df['ref_anomes'] = df['released_date'].dt.strftime('%d-%Y')

# df['streams'] = pd.to_numeric(df['streams'].astype(int)) investigação
print(f"Valores totais colunas 'streams': {df['streams'].unique()}")
#Aparentemente existe um valor estranho entre as cedulas (BPM110KeyAModeMajorDanceability53...) que esta impedindo a transformação de todas as colunas em INT

df['streams'] = df['streams'].replace('BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3', '0')
#O valor esta na linha 574, é possível observar que todos os outros valores desta linha estão integros
#A partir disso vamos substituir este valor pela média de todos os valores existentes nessa coluna

df['streams'] = df['streams'].replace('BPM110KeyAModeMajorDanceability53Valence75Energy69Acousticness7Instrumentalness0Liveness17Speechiness3', '0')
df['streams'] = df['streams'].astype(int)
df.mean_streams = df['streams'].mean()
df['streams'] = df['streams'].replace(0, df.mean_streams)

"""Após verificar a que o streams possui um valor estranho, por curiosidade também verifiquei as colunas in_deezer_charts, in_shazam_charts. Após a analise, concluo que todas estão OK."""

print(f"Colunas distintas em 'in_deezer_charts': {df['in_deezer_charts'].nunique()}")
print(f"Colunas unicas em 'in_deezer_charts': {df['in_deezer_charts'].unique()}")

print(f"Colunas distintas em 'in_shazam_charts': {df['in_shazam_charts'].nunique()}")
print(f"Colunas únicas em 'in_shazam_charts': {df['in_shazam_charts'].unique()}")

print(f"Colunas distintas em 'in_apple_charts': {df['in_apple_charts'].nunique()}")
print(f"Colunas unicas em 'in_apple_charts': {df['in_apple_charts'].unique()}")

"""### Fato passivel de investigação:
o número de reprodução de cada música tende a ser diferente, dificilmente vamos ver duas músicas tendo exatamente o mesmo número de reproduções. Como observado, existem 8 músicas com os exatos mesmo número de streams.
"""

print(f"Quantidade de aparições de cada valor da variável 'streams': {df['streams'].value_counts()}")

"""### Conclusão:
Após avaliar as músicas de que possuem seu número de reprodução repetida é possível verificar que são músicas iguais que apresentam diferenças como datas de lançamento, nome diferente, cantor diferente.
"""

valores = [723894473, 1223481149, 395591396, 156338624]

df_filtrado = df[df['streams'].isin(valores)]
df_filtrado.head()

"""###Correção Valores Nulos

Algumas colunas apresentam valores nulos, então é necessario entender o porque isso acontece:
- Os valores nulos estão em colunas que apresentam informações relevantes em toda sua linha, portanto exlcuir não torna uma opção segura
- Um das opções é substituir pela médiao e moda, mas como o valores nulos da variável 'in_shazam_charts' alcaçam 6% dos totais, enquanto a variavel 'key' chega a 10%, portanto, essa substituição pode enviesar futuros modelos que utilizem essa base de dado limpa.
- Nas colunas  'in_shazam_charts' a melhor opção seria a substituição por um valor discrepante de '9999' no qual, se destacara quando aparecer em alguma analise futura demonstrando a existencia dos valores nulos.
- Na coluna KEY substituiremos por 'miss_verificar' para demonstrar em futuras analises que este valor é nulo
"""

#Variavel 'in_shazam_charts'
df[df['in_shazam_charts'].isnull()].head(10)

df['in_shazam_charts'] = df['in_shazam_charts'].fillna(9999)
df['in_shazam_charts'] = df['in_shazam_charts'].astype(int)
df['in_shazam_charts'].isnull().sum()

#Variavel 'key'
print(f"Colunas distintas em 'key': {df['key'].nunique()}")
print(f"Colunas unicas em 'key': {df['key'].unique()}")

df[df['key'].isnull()].head(5)

df['key'] = df['key'].fillna('Miss_verificar')
df['key'].isnull().sum()

"""###Verificando se o tratamento inicial esta concluido
- Coluna informção esta com todas as variaveis corrigidas
- Nenhuma coluna apresenta mais valores nulos

"""

buffer = io.StringIO()
df.info(buf=buffer)


summary = pd.DataFrame({
    "Informação": df.dtypes,
    "Cardinalidade": df.nunique(),
    "Valores não nulos": df.notnull().sum(),
    "Dados Nulos": df.isnull().sum()
    })

print(summary)

"""##Analise estatistica


- **artist_count**: É possivel verificar que a maior parte dos artistas (75%) tem preferencia por cantar solo
  - No entando o máximo de artista que uma música contem é 8, essa é uma observação importante pois pode indicar outliers em analise futuras


- **Streams:**: O número de streams médio é de 513 milhões, no entanto existem músicas que estão muito a baixo com apenas 2762 streams. Isso demonstra uma alta dispersão na quantidade de reprodução de músicas.



-  **released_year**: A maior parte das músicas mais tocadas no Spotify foi lançada a partir de 2020. Esse padrão sugere que o consumo musical está fortemente concentrado em lançamentos recentes, indicando uma renovação constante das preferências do público.

- **Danceability, Energy, Valence, BPM**:
  - **BPM médio:** Em média as musicas que fazem mais sucesso apresentam um ritimo levemente acelerado (122BPM).
  - **Danceability média:** 67%  das músicas apresentam alto potencial para dança.
  - **Energy média:** 64% das músicas exibem alta intensidade sonora.







"""

df.describe()

"""##Insigts
  ### Média de presença em playlist por plataforma
- Podemos observar que o spotify é uma vitrine para os artistas, as músicas estão presentes nas playlits em maior quantidade nessa plataforma em relação as outras
  - Olhando pelo lado do artista é uma boa oportunidade a inclusão de seus singles nessa plataforma para alavancar sua composição
  ### Relação total de playlist x streams
- Há uma evidente correlação entre o numero de playlists que a música se encontra em relação a quantidade de streams que ela possui
  - Esse achado pode orientar decisões de investimento em curadoria de playlists e parcerias com criadores de conteúdo musical, buscando maximizar o retorno de streams
  ### Distribuição de lançamentos por Mês
- A concentração de lançamentos ocorre principalmente entre abril e maio. Quando pesquisado mais a fundo, observa-se que este período marca o início do verão no hemisfério norte, uma das épocas de maior consumo de música devido ao aumento de eventos ao ar livre, festivais e atividades sociais.
  - Por outro lado, meses como agosto e setembro apresentam queda no número de lançamentos, o que pode representar uma janela de oportunidade competitiva para novos artistas ou gravadoras buscarem maior destaque com menor saturação do mercado.
"""

sns.set_style("white")

# --- Gráfico 1: Média de presenças em playlist por plataforma ---
plataformas = {
    'in_spotify_playlists': 'Spotify',
    'in_apple_playlists': 'Apple M.',
    'in_deezer_playlists': 'Deezer'
}
media_plataformas = df[list(plataformas.keys())].mean().rename(index=plataformas).sort_values(ascending=False)

# Produção da variavel
df['total_playlists'] = df[['in_spotify_playlists', 'in_apple_playlists', 'in_deezer_playlists']].sum(axis=1)

# Criação da figura
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
sns.barplot(
    x=media_plataformas.index,
    y=media_plataformas.values,
    palette='Blues',
    ax=axes[0]
)
axes[0].set_title("Média de presença em playlists por plataforma")
axes[0].set_xlabel("Plataforma")
axes[0].set_ylabel("Média de playlists por música")
axes[0].grid(False)

# --- Gráfico 2: Relação total de playlists x streams ---
sns.scatterplot(
    x='total_playlists',
    y='streams',
    data=df,
    alpha=0.6,
    color='blue',
    ax=axes[1]
)
axes[1].set_title("Relação Playlists x Streams")
axes[1].set_xlabel("Total de playlists")
axes[1].set_ylabel("Streams")
axes[1].set_xscale('log')
axes[1].set_yscale('log')
axes[1].grid(False)

# --- Gráfico 3: Distribuição de lançamentos por mês ---
sns.countplot(
    x='released_month',
    data=df,
    hue='released_month',
    palette='Blues',
    legend=False,
    ax=axes[2]
)
axes[2].set_title("Distribuição de lançamentos por mês")
axes[2].set_xlabel("Mês de lançamento")
axes[2].set_ylabel("Quantidade de músicas")
axes[2].grid(False)


plt.tight_layout()
plt.show()

"""###Correlação entre características musicais
- As correlações são baixas, o que sugere que nenhum atributo isolado explica sozinho o sucesso de uma música.
- Ainda assim, um ponto chamou atenção: a correlação negativa de -0.58 entre “energy_%” e “acousticness_%”, pode até ser obvio, mas é interessante pensa quer músicas mais energéticas tendem a ter produções acústicas
"""

cols_musicais = ['bpm','danceability_%', 'valence_%', 'energy_%', 'acousticness_%']
sns.heatmap(df[cols_musicais].corr(), annot=True, cmap="YlGnBu", fmt=".2f")
plt.title("Correlação entre características musicais")
plt.show()

"""##Insigts
- **track_name**: Dos 953 registros, temos 943 nomes únicos, mas é possível observar 10 músicas repetidas.
  - Ao analisar mais detalhadamente essas músicas, é possível perceber que se tratam de versões interpretadas por artistas diferentes ou de variações da mesma faixa produzidas pelo próprio artista, em tonalidades distintas.

- **artist(s)_name**: 645 artistas únicos em 953 músicas(média de cerca de 1,47 músicas por artista.)
  - Alguns artistas apresentam presença dominante nas playlists, o que pode indicar talvez uma fã base muito forte ou uma qualidade expecional na produção dos seus singles.
"""

df.describe(include=['object'])

# Músicas que aparecem mais de uma vez
duplicadas = df[df.duplicated(subset=['track_name'], keep=False)]

duplicadas.sort_values('track_name').head(20)

"""## Datas com maior lançamento de HITS
- No ano de 2022 foi o ano com a maior quantidade de HITS historicos, com cerca de 77% das músicas mais tocadas lançandas neste periodo.
  - Uma reflexão do porque isso pode ter acontecido:
    - Explosão dos streamings, principalmente por decorrencia da pandemia da covid 19
    
## Artistas mais tocados
- Observamos que a Taylor sem sal, digo Taylor Swift foi a artista com maior número de faixas entre as mais tocadas
- Nota-se também que não há uma dominância clara de um único estilo musical. O conjunto de artistas e faixas analisadas apresenta diversidade de gêneros, abrangendo pop, hip hop, reggaeton, R&B e outros, o que evidencia o caráter eclético e globalizado do consumo musical na plataforma.



"""

# Cálculo da média móvel
rolling = counts_by_year.rolling(window=3).mean()

# Criação da figura
fig, axes = plt.subplots(2, 1, figsize=(10, 8))

# --- Gráfico 1 ---
axes[0].bar(counts_by_year.index, counts_by_year.values,
            color='darkblue', label='Lançamentos por ano')
axes[0].plot(rolling.index, rolling.values,
             color='red', linewidth=1, alpha=0.7, label='Média móvel (3 anos)')
axes[0].set_title('Tendência de lançamentos musicais')
axes[0].set_xlabel('Ano')
axes[0].set_ylabel('Quantidade de músicas')
axes[0].legend()
fig.lines.append(plt.Line2D([0.05, 0.95], [0.5, 0.5],
                            color='gray', linewidth=0.8, alpha=0.6,
                            transform=fig.transFigure))

# --- Gráfico 2 ---
df['artist(s)_name'].value_counts().head(10).plot(
    kind='barh', color='darkblue', ax=axes[1])
axes[1].set_title('Top 10 artistas com mais músicas entre as mais tocadas')
axes[1].set_xlabel('Quantidade de faixas')
axes[1].set_ylabel('Artista')
plt.tight_layout()
plt.show()